import './globals.css';
import { Poppins} from 'next/font/google';

const poppins = Poppins({
  weight : ["400","500", "600", "700", "800", "900"],
  display : "swap",
  subsets : ["latin"]
})

export const metadata = {
  title: 'Tailwind CSS Components - Tailwind UI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative antialiased`}>
         
        <main className='mx-auto relative lg:px-2 px-5 max-w-7xl w-full py-6'>
        {children}
        </main>
        </body>
    </html>
  )
}
